orth: Gracefully handle initializing with unexpected file extension
Print an error message an exit in case the file extension is unexpected.

Signed-off-by: Frank Viernau <frank_viernau@epam.com>

diff --git a/orthw b/orthw
--- a/orthw
+++ b/orthw
@@ -391,6 +391,9 @@ init() {
     mv $temp_scan_result_file $scan_result_file
   elif [[ "$extension" == "yml" ]]; then
     orth convert-ort-file -i $temp_scan_result_file -o $scan_result_file
+  else
+    echo "Cannot initialize with the given file '$filename'. The file extension is unexpected."
+    exit 1
   fi
 
   orth extract-repository-configuration \
